app:
  build: .
  command: sh -c "npm install && npm test -- --hostname chrome"
  links:
    - chrome
  volumes:
    - .:/usr/test
  working_dir: /usr/test

chrome:
  image: selenium/standalone-chrome
  expose:
    - '4444'
